// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrb8LWlFXWdYghCESTwtoXoXZyPgFCDpY',
    appId: '1:594972629856:web:1c3dff3e3835e9e6d11c05',
    messagingSenderId: '594972629856',
    projectId: 'trial-d5401',
    authDomain: 'trial-d5401.firebaseapp.com',
    storageBucket: 'trial-d5401.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdaRFtswmPzEzKTXSwPkYEsBTGRe4Er2E',
    appId: '1:594972629856:android:906aa9615277a8f9d11c05',
    messagingSenderId: '594972629856',
    projectId: 'trial-d5401',
    storageBucket: 'trial-d5401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfxuSghRGGE4Cp9mv7A3YS3kbRACfXW7o',
    appId: '1:594972629856:ios:19f298020df216afd11c05',
    messagingSenderId: '594972629856',
    projectId: 'trial-d5401',
    storageBucket: 'trial-d5401.appspot.com',
    androidClientId: '594972629856-e94uoplujs79n1n64oan9dkngvvsb9g3.apps.googleusercontent.com',
    iosClientId: '594972629856-e5fv7ol4e33pcstvaieo6cglmtu2ig17.apps.googleusercontent.com',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfxuSghRGGE4Cp9mv7A3YS3kbRACfXW7o',
    appId: '1:594972629856:ios:19f298020df216afd11c05',
    messagingSenderId: '594972629856',
    projectId: 'trial-d5401',
    storageBucket: 'trial-d5401.appspot.com',
    androidClientId: '594972629856-e94uoplujs79n1n64oan9dkngvvsb9g3.apps.googleusercontent.com',
    iosClientId: '594972629856-e5fv7ol4e33pcstvaieo6cglmtu2ig17.apps.googleusercontent.com',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrb8LWlFXWdYghCESTwtoXoXZyPgFCDpY',
    appId: '1:594972629856:web:b08c0582b2813a21d11c05',
    messagingSenderId: '594972629856',
    projectId: 'trial-d5401',
    authDomain: 'trial-d5401.firebaseapp.com',
    storageBucket: 'trial-d5401.appspot.com',
  );

}